In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split

In [61]:
data = pd.read_csv("kc_house_data.csv")

In [63]:
data

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [65]:
X = data.iloc[:, : -1].values

In [67]:
Y = data.iloc[:, -1].values

In [69]:
X


array([[7129300520, '20141013T000000', 221900.0, ..., 47.5112, -122.257,
        1340],
       [6414100192, '20141209T000000', 538000.0, ..., 47.721, -122.319,
        1690],
       [5631500400, '20150225T000000', 180000.0, ..., 47.7379, -122.233,
        2720],
       ...,
       [1523300141, '20140623T000000', 402101.0, ..., 47.5944, -122.299,
        1020],
       [291310100, '20150116T000000', 400000.0, ..., 47.5345, -122.069,
        1410],
       [1523300157, '20141015T000000', 325000.0, ..., 47.5941, -122.299,
        1020]], dtype=object)

In [71]:
Y

array([5650, 7639, 8062, ..., 2007, 1287, 1357], dtype=int64)

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [75]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [3])], remainder= 'passthrough')

In [77]:
X = np.array(ct.fit_transform(X))

In [79]:
X

array([[0.0, 0.0, 0.0, ..., 47.5112, -122.257, 1340],
       [0.0, 0.0, 0.0, ..., 47.721, -122.319, 1690],
       [0.0, 0.0, 1.0, ..., 47.7379, -122.233, 2720],
       ...,
       [0.0, 0.0, 1.0, ..., 47.5944, -122.299, 1020],
       [0.0, 0.0, 0.0, ..., 47.5345, -122.069, 1410],
       [0.0, 0.0, 1.0, ..., 47.5941, -122.299, 1020]], dtype=object)

In [81]:
X_train, Y_train, X_test, Y_test = train_test_split(X,Y, test_size= 0.2,random_state= 42)

In [83]:
X_train


array([[0.0, 0.0, 0.0, ..., 47.367, -122.152, 2750],
       [0.0, 0.0, 1.0, ..., 47.552, -122.29, 1270],
       [0.0, 0.0, 0.0, ..., 47.4838, -122.335, 1170],
       ...,
       [0.0, 0.0, 0.0, ..., 47.681, -122.032, 1690],
       [0.0, 1.0, 0.0, ..., 47.481, -122.323, 1170],
       [0.0, 0.0, 0.0, ..., 47.3837, -122.099, 3020]], dtype=object)

In [85]:
Y_train

array([[0.0, 0.0, 0.0, ..., 47.4388, -122.162, 2390],
       [0.0, 0.0, 0.0, ..., 47.6784, -122.285, 2370],
       [0.0, 0.0, 0.0, ..., 47.5646, -122.129, 3710],
       ...,
       [0.0, 0.0, 0.0, ..., 47.2874, -122.283, 2434],
       [0.0, 0.0, 0.0, ..., 47.5922, -122.118, 2050],
       [0.0, 0.0, 0.0, ..., 47.2809, -122.296, 2430]], dtype=object)

In [87]:
len(X_train)

17290

In [89]:
len(Y_train)

4323

In [91]:
reg = LinearRegression()

In [103]:
reg.fit(X_train, Y_train)

ValueError: could not convert string to float: '20140527T000000'