In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [46]:
data = pd.read_csv("Logistic Regression.csv")

In [48]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   50            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [50]:
X = data.iloc[:, :-1].values

In [52]:
Y = data.iloc[:, -1].values

In [54]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    21,  18000],
       [    18,  20000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [56]:
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [71]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25,random_state=0)

In [73]:
len(X_train)

300

In [75]:
len(X_test)

100

In [77]:
sc = StandardScaler()

In [79]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [81]:
X_test

array([[-0.54748976,  0.52629258],
       [ 0.15442019, -0.59283532],
       [-0.10879604,  0.16333218],
       [-0.54748976,  0.28431898],
       [-0.10879604, -0.59283532],
       [-0.81070599, -1.50023632],
       [-0.45975102, -1.65146982],
       [-0.0210573 ,  2.25035448],
       [-1.60035469, -0.04839472],
       [ 0.94406888, -0.80456222],
       [-0.54748976, -0.62308202],
       [-0.72296725, -0.44160182],
       [ 0.06668145, -0.44160182],
       [ 0.24215893,  0.22382558],
       [-1.4248772 ,  0.49604588],
       [-0.37201227,  1.43369358],
       [ 0.06668145,  0.22382558],
       [-1.51261594,  0.46579918],
       [ 1.64597884,  1.82690068],
       [-0.10879604, -1.43974292],
       [-0.10879604, -0.68357542],
       [ 0.94406888,  2.25035448],
       [ 0.41763642, -0.56258862],
       [ 0.94406888,  1.07073318],
       [-1.16166097, -1.25826272],
       [ 1.11954637,  2.15961438],
       [-0.72296725,  0.52629258],
       [-0.63522851,  0.31456568],
       [ 0.06668145,

In [86]:
X_train

array([[ 0.56128498, -0.88866732],
       [-0.60738242,  1.46548245],
       [-0.02304872, -0.56896797],
       [-0.60738242,  1.90143611],
       [ 1.34039657, -1.41181171],
       [ 1.43778552,  1.00046521],
       [ 0.07434023, -0.80147659],
       [-0.02304872, -0.24926862],
       [-0.21782662, -0.56896797],
       [-0.21782662, -0.19114146],
       [-0.31521557, -1.2955574 ],
       [-0.31521557, -0.56896797],
       [ 0.36650708,  0.09949431],
       [ 0.85345183, -0.59803154],
       [ 2.02211922, -1.17930309],
       [ 1.04822973, -0.13301431],
       [ 0.65867393,  1.7851818 ],
       [-0.70477136,  0.56451155],
       [ 0.75606288,  0.36106651],
       [ 0.85345183, -0.53990439],
       [-1.19171611, -1.58619318],
       [ 2.11950817,  0.94233806],
       [-0.02304872,  1.23297383],
       [ 0.17172918,  1.08765595],
       [ 0.36650708, -0.48177724],
       [-0.31521557, -0.30739577],
       [ 0.95084078, -0.83054016],
       [ 0.95084078,  1.87237254],
       [-0.02304872,

In [88]:
from sklearn.svm import SVC

In [92]:
reg = SVC(kernel = 'linear', random_state = 0)

In [94]:
reg.fit(X_train, Y_train)

SVC(kernel='linear', random_state=0)

In [96]:
print(reg.predict(sc.transform([[32,150000]]))[0])

1


In [98]:
print(reg.predict(sc.transform([[20,86000]]))[0])

0


In [102]:
Y_pred = reg.predict(X_test)

In [104]:
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [106]:
print(np.concatenate((Y_pred.reshape(len(Y_pred), 1), Y_test.reshape(len(Y_test), 1)), 1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [108]:
cm = confusion_matrix(Y_test, Y_pred)

In [110]:
cm

array([[64,  4],
       [ 7, 25]], dtype=int64)

In [112]:
accuracy_score(Y_test,Y_pred)

0.89

In [114]:
reg.predict(X_train)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

# There are many more types like 

#SVM

#K-Neareset Neighors(KNN)

#Kernel SVM

#Naive Boyes

#Decision Tree Classification

#Random forest Classification